In [4]:
#read csv
import pandas as pd

In [5]:
df=pd.read_csv('student.csv')

In [6]:
df

   S.N     Name  Age City
0    1   Rakesh   35  Ktm
1    2  Prakash   30  Bkt
2    3   Barsha   28  Ltp
3    4    Sneha   20  Ktm
4    5  Abhiyan   32  Brt
5    6   Anisha   40  Ltp
6    7   Parash   50  Rjb
7    8    Kiran   60  Brt
8    9      Ram   42  NaN

In [7]:
print(df.head(5))
print(df.tail(5))

   S.N     Name  Age City
0    1   Rakesh   35  Ktm
1    2  Prakash   30  Bkt
2    3   Barsha   28  Ltp
3    4    Sneha   20  Ktm
4    5  Abhiyan   32  Brt
   S.N     Name  Age City
4    5  Abhiyan   32  Brt
5    6   Anisha   40  Ltp
6    7   Parash   50  Rjb
7    8    Kiran   60  Brt
8    9      Ram   42  NaN

In [8]:
df.info() #show information of data

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   S.N     9 non-null      int64
 1   Name    9 non-null      str
 2   Age     9 non-null      int64
 3   City    8 non-null      str
dtypes: int64(2), str(2)
memory usage: 420.0 bytes

In [9]:
df.describe() #statistical information of data

            S.N        Age
count  9.000000   9.000000
mean   5.000000  37.444444
std    2.738613  12.135806
min    1.000000  20.000000
25%    3.000000  30.000000
50%    5.000000  35.000000
75%    7.000000  42.000000
max    9.000000  60.000000

In [10]:
df.isnull().sum() #count of missing value

S.N     0
Name    0
Age     0
City    1
dtype: int64

In [11]:
df.count

<bound method DataFrame.count of    S.N     Name  Age City
0    1   Rakesh   35  Ktm
1    2  Prakash   30  Bkt
2    3   Barsha   28  Ltp
3    4    Sneha   20  Ktm
4    5  Abhiyan   32  Brt
5    6   Anisha   40  Ltp
6    7   Parash   50  Rjb
7    8    Kiran   60  Brt
8    9      Ram   42  NaN>

In [12]:
df['Name'].unique #repeated name will be only shown once

<bound method Series.unique of 0     Rakesh
1    Prakash
2     Barsha
3      Sneha
4    Abhiyan
5     Anisha
6     Parash
7      Kiran
8        Ram
Name: Name, dtype: str>

In [13]:
df.columns

Index(['S.N', 'Name', 'Age', 'City'], dtype='str')

In [14]:
df['City'].value_counts() #counts of entry of the city

City
Ktm    2
Ltp    2
Brt    2
Bkt    1
Rjb    1
Name: count, dtype: int64