In [34]:
#data transformation
import pandas as pd

In [35]:
df=pd.DataFrame({
    'Name':['Kali','Sikha','Anisha','Priya','Anya','Anya'],
    'Age':[25,30,22,28,35,5],
    'Salary':[5000,7000,4500,6500,8000,2000],
    'City':['Rjb','Brt','Ktm','Pkr','Ktm','Pkr']
})

In [36]:
df

     Name  Age  Salary City
0    Kali   25    5000  Rjb
1   Sikha   30    7000  Brt
2  Anisha   22    4500  Ktm
3   Priya   28    6500  Pkr
4    Anya   35    8000  Ktm
5    Anya    5    2000  Pkr

In [37]:
df['Bonus']=df['Salary']*0.10 #add bonus in table

In [38]:
df

     Name  Age  Salary City  Bonus
0    Kali   25    5000  Rjb  500.0
1   Sikha   30    7000  Brt  700.0
2  Anisha   22    4500  Ktm  450.0
3   Priya   28    6500  Pkr  650.0
4    Anya   35    8000  Ktm  800.0
5    Anya    5    2000  Pkr  200.0

In [39]:
df['Name']=df['Name'].str.upper() #name in capital letter

In [40]:
df

     Name  Age  Salary City  Bonus
0    KALI   25    5000  Rjb  500.0
1   SIKHA   30    7000  Brt  700.0
2  ANISHA   22    4500  Ktm  450.0
3   PRIYA   28    6500  Pkr  650.0
4    ANYA   35    8000  Ktm  800.0
5    ANYA    5    2000  Pkr  200.0

In [41]:
df['Name']=df['Name'].str.lower() #lower case letter

In [42]:
df

     Name  Age  Salary City  Bonus
0    kali   25    5000  Rjb  500.0
1   sikha   30    7000  Brt  700.0
2  anisha   22    4500  Ktm  450.0
3   priya   28    6500  Pkr  650.0
4    anya   35    8000  Ktm  800.0
5    anya    5    2000  Pkr  200.0

In [43]:
df['Name']=df['Name'].str.title() #first letter capital all small

In [44]:
df

     Name  Age  Salary City  Bonus
0    Kali   25    5000  Rjb  500.0
1   Sikha   30    7000  Brt  700.0
2  Anisha   22    4500  Ktm  450.0
3   Priya   28    6500  Pkr  650.0
4    Anya   35    8000  Ktm  800.0
5    Anya    5    2000  Pkr  200.0

In [45]:
df['City']=df['City'].replace('Ktm','Ktm capital') #replace the cell with different value

In [46]:
df

     Name  Age  Salary         City  Bonus
0    Kali   25    5000          Rjb  500.0
1   Sikha   30    7000          Brt  700.0
2  Anisha   22    4500  Ktm capital  450.0
3   Priya   28    6500          Pkr  650.0
4    Anya   35    8000  Ktm capital  800.0
5    Anya    5    2000          Pkr  200.0

In [47]:
gender={
    'Kali':'Female',
    'Sikha':'Female',
    'Anisha':'Female',
    'Priya':'Female',
    'Anya':'Female'
}

In [48]:
df['Gender']=df['Name'].map(gender)

In [49]:
df

     Name  Age  Salary         City  Bonus  Gender
0    Kali   25    5000          Rjb  500.0  Female
1   Sikha   30    7000          Brt  700.0  Female
2  Anisha   22    4500  Ktm capital  450.0  Female
3   Priya   28    6500          Pkr  650.0  Female
4    Anya   35    8000  Ktm capital  800.0  Female
5    Anya    5    2000          Pkr  200.0  Female

In [50]:
df['City']=df['City'].replace('Ktm capital','Ktm')
df

     Name  Age  Salary City  Bonus  Gender
0    Kali   25    5000  Rjb  500.0  Female
1   Sikha   30    7000  Brt  700.0  Female
2  Anisha   22    4500  Ktm  450.0  Female
3   Priya   28    6500  Pkr  650.0  Female
4    Anya   35    8000  Ktm  800.0  Female
5    Anya    5    2000  Pkr  200.0  Female

In [51]:
df['Name'].unique()

<StringArray>
['Kali', 'Sikha', 'Anisha', 'Priya', 'Anya']
Length: 5, dtype: str

In [52]:
df['Age_Months']=df['Age']*12
df

     Name  Age  Salary City  Bonus  Gender  Age_Months
0    Kali   25    5000  Rjb  500.0  Female         300
1   Sikha   30    7000  Brt  700.0  Female         360
2  Anisha   22    4500  Ktm  450.0  Female         264
3   Priya   28    6500  Pkr  650.0  Female         336
4    Anya   35    8000  Ktm  800.0  Female         420
5    Anya    5    2000  Pkr  200.0  Female          60

In [53]:
sorted_df=df.sort_values(by='Age',inplace=True) #sorting (by default its always ascending)
sorted_df

In [54]:
sorted_df=df.sort_values(by='Age',ascending=False) #sorting in descending
sorted_df

     Name  Age  Salary City  Bonus  Gender  Age_Months
4    Anya   35    8000  Ktm  800.0  Female         420
1   Sikha   30    7000  Brt  700.0  Female         360
3   Priya   28    6500  Pkr  650.0  Female         336
0    Kali   25    5000  Rjb  500.0  Female         300
2  Anisha   22    4500  Ktm  450.0  Female         264
5    Anya    5    2000  Pkr  200.0  Female          60

In [55]:
df.sort_values(by=['Age','Salary'],ascending=[False,True],inplace=True)

In [56]:
df

     Name  Age  Salary City  Bonus  Gender  Age_Months
4    Anya   35    8000  Ktm  800.0  Female         420
1   Sikha   30    7000  Brt  700.0  Female         360
3   Priya   28    6500  Pkr  650.0  Female         336
0    Kali   25    5000  Rjb  500.0  Female         300
2  Anisha   22    4500  Ktm  450.0  Female         264
5    Anya    5    2000  Pkr  200.0  Female          60

In [57]:
df.sort_values(by=['Salary','Age'],ascending=[True,False],inplace=True) #inplace is for placing the changes data in the dataframe

In [58]:
df

     Name  Age  Salary City  Bonus  Gender  Age_Months
5    Anya    5    2000  Pkr  200.0  Female          60
2  Anisha   22    4500  Ktm  450.0  Female         264
0    Kali   25    5000  Rjb  500.0  Female         300
3   Priya   28    6500  Pkr  650.0  Female         336
1   Sikha   30    7000  Brt  700.0  Female         360
4    Anya   35    8000  Ktm  800.0  Female         420

In [59]:
sorted_df=df.sort_values(by='City') 
sorted_df

     Name  Age  Salary City  Bonus  Gender  Age_Months
1   Sikha   30    7000  Brt  700.0  Female         360
2  Anisha   22    4500  Ktm  450.0  Female         264
4    Anya   35    8000  Ktm  800.0  Female         420
5    Anya    5    2000  Pkr  200.0  Female          60
3   Priya   28    6500  Pkr  650.0  Female         336
0    Kali   25    5000  Rjb  500.0  Female         300

In [60]:
df=df.sort_values(by='Age').reset_index(drop=True)
df

     Name  Age  Salary City  Bonus  Gender  Age_Months
0    Anya    5    2000  Pkr  200.0  Female          60
1  Anisha   22    4500  Ktm  450.0  Female         264
2    Kali   25    5000  Rjb  500.0  Female         300
3   Priya   28    6500  Pkr  650.0  Female         336
4   Sikha   30    7000  Brt  700.0  Female         360
5    Anya   35    8000  Ktm  800.0  Female         420

In [61]:
df=df[df['Age']>25]

In [62]:
df

    Name  Age  Salary City  Bonus  Gender  Age_Months
3  Priya   28    6500  Pkr  650.0  Female         336
4  Sikha   30    7000  Brt  700.0  Female         360
5   Anya   35    8000  Ktm  800.0  Female         420

In [63]:
df=df[(df['Age']>25) & (df['Salary']>5000)]
df

    Name  Age  Salary City  Bonus  Gender  Age_Months
3  Priya   28    6500  Pkr  650.0  Female         336
4  Sikha   30    7000  Brt  700.0  Female         360
5   Anya   35    8000  Ktm  800.0  Female         420

In [64]:
#display all record from the df where age is greater than 22 and city is ktm

In [66]:
df=df[(df['Age']>22) & (df['City']=='Ktm')]
df

Empty DataFrame
Columns: [Name, Age, Salary, City, Bonus, Gender, Age_Months]
Index: []