In [183]:
#data cleaning

In [184]:
import pandas as pd
import numpy as np

In [328]:
data={
    "Name":['Samu','Kali','Samu','Gita','None'],
    "Age":[25,30,25,30,28],
    "City":['KTM','BRT','KTM',None,'Dhg'],
    "Salary":[5000,6000,5000,np.nan,60000]
}

In [329]:
df=pd.DataFrame(data)

In [330]:
df
cpydf=df

In [331]:
df.isnull()

    Name    Age   City  Salary
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False
3  False  False   True    True
4  False  False  False   False

In [332]:
df.isnull().sum

<bound method DataFrame.sum of     Name    Age   City  Salary
0  False  False  False   False
1  False  False  False   False
2  False  False  False   False
3  False  False   True    True
4  False  False  False   False>

In [333]:
df.dropna() #removing null

   Name  Age City   Salary
0  Samu   25  KTM   5000.0
1  Kali   30  BRT   6000.0
2  Samu   25  KTM   5000.0
4  None   28  Dhg  60000.0

In [334]:
cdf=df.dropna(axis=1)

In [335]:
cdf

   Name  Age
0  Samu   25
1  Kali   30
2  Samu   25
3  Gita   30
4  None   28

In [336]:
df_clean=df.dropna(axis=0)
df_clean

   Name  Age City   Salary
0  Samu   25  KTM   5000.0
1  Kali   30  BRT   6000.0
2  Samu   25  KTM   5000.0
4  None   28  Dhg  60000.0

In [337]:
#filling the missing value

In [338]:
dfzero=df.fillna(0) #replacing missing value with zero

In [339]:
dfzero

   Name  Age City   Salary
0  Samu   25  KTM   5000.0
1  Kali   30  BRT   6000.0
2  Samu   25  KTM   5000.0
3  Gita   30    0      0.0
4  None   28  Dhg  60000.0

In [340]:
df

   Name  Age City   Salary
0  Samu   25  KTM   5000.0
1  Kali   30  BRT   6000.0
2  Samu   25  KTM   5000.0
3  Gita   30  NaN      NaN
4  None   28  Dhg  60000.0

In [341]:
age_mean=df['Age'].mean()

In [342]:
age_mean

np.float64(27.6)

In [343]:
df['Age']=df['Age'].fillna(age_mean)

In [344]:
df['Age']

0    25
1    30
2    25
3    30
4    28
Name: Age, dtype: int64

In [345]:
df

   Name  Age City   Salary
0  Samu   25  KTM   5000.0
1  Kali   30  BRT   6000.0
2  Samu   25  KTM   5000.0
3  Gita   30  NaN      NaN
4  None   28  Dhg  60000.0

In [346]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [347]:
df['Age']

0    25
1    30
2    25
3    30
4    28
Name: Age, dtype: int64

In [348]:
df

   Name  Age City   Salary
0  Samu   25  KTM   5000.0
1  Kali   30  BRT   6000.0
2  Samu   25  KTM   5000.0
3  Gita   30  NaN      NaN
4  None   28  Dhg  60000.0

In [349]:
cpydf

   Name  Age City   Salary
0  Samu   25  KTM   5000.0
1  Kali   30  BRT   6000.0
2  Samu   25  KTM   5000.0
3  Gita   30  NaN      NaN
4  None   28  Dhg  60000.0

In [350]:
# df=df.ffill() #forward fill (will fill up the nan with the previous value)
# df

In [351]:
df=df.bfill()
df

   Name  Age City   Salary
0  Samu   25  KTM   5000.0
1  Kali   30  BRT   6000.0
2  Samu   25  KTM   5000.0
3  Gita   30  Dhg  60000.0
4  None   28  Dhg  60000.0

In [352]:
dup=df.duplicated() #find the duplicate value
dup

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [354]:
df=df.drop_duplicates() #revove the duplicated value
df

   Name  Age City   Salary
0  Samu   25  KTM   5000.0
1  Kali   30  BRT   6000.0
3  Gita   30  Dhg  60000.0
4  None   28  Dhg  60000.0