In [65]:
#encoding 
#encoding catergorical data: one hot encoding and label encoding::
#categorical data is data that contains categories (text values) instead of numbers
#machine learning algorithms cannot work directly with text, so we convert categorical values into numbers using encoding
# 1. One-hot Encoding(for normal data)
# 2. Ordinal Encoding(for ordinal data)
# !pip install scikit-learn

In [66]:
import pandas as pd
df=pd.DataFrame({
    "Color":['red','blue','green','blue','red']
})
df

   Color
0    red
1   blue
2  green
3   blue
4    red

In [67]:
from sklearn.preprocessing import OneHotEncoder

In [68]:
encoder=OneHotEncoder(sparse_output=False)
encoded=encoder.fit_transform(df[['Color']])
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [69]:
encoded_df=pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(["Color"])
)
encoded_df

   Color_blue  Color_green  Color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0

In [70]:
encoder=OneHotEncoder(drop="first",sparse_output=False)
encoded=encoder.fit_transform(df[["Color"]])
encoded

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

In [71]:
from sklearn.preprocessing import OrdinalEncoder
df=pd.DataFrame({
    "Size":['small','medium','large','medium','small']
})
df

     Size
0   small
1  medium
2   large
3  medium
4   small

In [72]:
encoder=OrdinalEncoder(
    categories=[['small','medium','large']]
)
df['size']=encoder.fit_transform(df[["Size"]])
df

     Size  size
0   small   0.0
1  medium   1.0
2   large   2.0
3  medium   1.0
4   small   0.0

In [73]:
df=pd.DataFrame({
    "result":['pass','fail','pass','fail','pass']
})
df

  result
0   pass
1   fail
2   pass
3   fail
4   pass

In [74]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df["Result"]=encoder.fit_transform(df['result'])
df

  result  Result
0   pass       1
1   fail       0
2   pass       1
3   fail       0
4   pass       1

In [75]:
decoded=encoder.inverse_transform(df["Result"])
decoded

array(['pass', 'fail', 'pass', 'fail', 'pass'], dtype=object)

In [76]:
df=pd.DataFrame({
    "Gender":['male','female','female','male'],
    "Size":['small','medium','large','medium'],
    "Result":['pass','fail','pass','dropout']
})

In [85]:
ohe=OneHotEncoder(drop='first',sparse_output=False)
gender_encoded=ohe.fit_transform(df[['Gender']])
gender_encoded

array([[1.],
       [0.],
       [0.],
       [1.]])

In [84]:
gender_df=pd.DataFrame(
    gender_encoded,
    columns=ohe.get_feature_names_out(["Gender"])
)

In [83]:
oe=OrdinalEncoder(categories=[['small','medium','large']])
df['size']=oe.fit_transform(df[['Size']])
df

   Gender    Size   Result  size  result
0    male   small     pass   0.0       2
1  female  medium     fail   1.0       1
2  female   large     pass   2.0       2
3    male  medium  dropout   1.0       0

In [82]:
le=LabelEncoder()
df['result']=le.fit_transform(df["Result"])
df

   Gender    Size   Result  size  result
0    male   small     pass   0.0       2
1  female  medium     fail   1.0       1
2  female   large     pass   2.0       2
3    male  medium  dropout   1.0       0

In [86]:
df=pd.concat([df.drop("Gender",axis=1),gender_df],axis=1)
df

     Size   Result  size  result  Gender_male
0   small     pass   0.0       2          1.0
1  medium     fail   1.0       1          0.0
2   large     pass   2.0       2          0.0
3  medium  dropout   1.0       0          1.0