In [3]:
#read excel sheet
import pandas as pd
df=pd.read_excel('sales_dataset.xlsx')

In [4]:
df

,OrderID,Date,Customer,City,Product,Category,Quantity,Price,Profit
0,1001,2024-03-30,Asha,Kathmandu,Phone,Electronics,4,500,284.04
1,1002,2024-03-01,Gita,Bhaktapur,Pen,Stationery,3,2,0.43
2,1003,2024-05-09,Hari,Kathmandu,Table,Furniture,4,250,56.34
3,1004,2024-01-30,Rita,Kathmandu,Notebook,Stationery,4,5,1.41
4,1005,2024-06-19,Hari,Kathmandu,Tablet,Electronics,4,300,145.43
5,1006,2024-05-09,Rita,Bhaktapur,Phone,Electronics,2,500,220.75
6,1007,2024-03-17,Gita,Kathmandu,Pen,Stationery,5,2,2.36
7,1008,2024-06-10,Hari,Lalitpur,Laptop,Electronics,2,800,271.43
8,1009,2024-06-08,Sita,Kathmandu,Pen,Stationery,2,2,0.85
9,1010,2024-02-06,Hari,Kathmandu,Chair,Furniture,5,120,78.66
10,1011,2024-06-13,Shyam,Kathmandu,Table,Furniture,5,250,183.74
11,1012,2024-02-17,Asha,Lalitpur,Pen,Stationery,4,2,1.13
12,1013,2024-03-13,Asha,Lalitpur,Table,Furniture,2,250,101.47
13,1014,2024-02-06,Ram,Bhaktapur,Notebook,Stationery,5,5,4.52
14,1015,2024-03-31,Hari,Kathmandu,Pen,Stationery,1,2,0.15
15,1016,2024-02-25,Nabin,Kathmandu,Chair,Furniture,3,120,60.54
16,1017,2024-01-02,Asha,Kathmandu,Table,Furniture,5,250,195.71
17,1018,2024-04-30,Ram,Kathmandu,Notebook,Stationery,5,5,1.31
18,1019,2024-01-24,Asha,Kathmandu,Table,Furniture,3,250,153.04
19,1020,2024-04-30,Ram,Lalitpur,Pen,Stationery,1,2,0.38
20,1021,2024-03-28,Hari,Kathmandu,Laptop,Electronics,3,800,513.27
21,1022,2024-06-28,Rita,Bhaktapur,Laptop,Electronics,1,800,177.65
22,1023,2024-03-16,Sita,Bhaktapur,Chair,Furniture,2,120,40.30
23,1024,2024-04-06,Gita,Kathmandu,Chair,Furniture,2,120,14.01
24,1025,2024-05-21,Hari,Bhaktapur,Chair,Furniture,4,120,54.19
25,1026,2024-06-27,Gita,Kathmandu,Notebook,Stationery,5,5,4.60
26,1027,2024-03-05,Ram,Kathmandu,Chair,Furniture,3,120,78.27
27,1028,2024-06-09,Shyam,Lalitpur,Table,Furniture,1,250,15.68
28,1029,2024-01-06,Hari,Lalitpur,Laptop,Electronics,3,800,137.76
29,1030,2024-01-02,Rita,Bhaktapur,Tablet,Electronics,3,300,213.99
30,1031,2024-02-20,Nabin,Kathmandu,Notebook,Stationery,5,5,3.64
31,1032,2024-02-11,Sita,Lalitpur,Table,Furniture,3,250,167.86
32,1033,2024-04-09,Asha,Bhaktapur,Phone,Electronics,5,500,511.12
33,1034,2024-02-01,Sita,Lalitpur,Phone,Electronics,3,500,268.76
34,1035,2024-01-31,Gita,Kathmandu,Tablet,Electronics,4,300,90.79
35,1036,2024-01-15,Asha,Bhaktapur,Tablet,Electronics,3,300,68.43
36,1037,2024-03-28,Asha,Lalitpur,Chair,Furniture,4,120,72.44
37,1038,2024-06-15,Sita,Lalitpur,Chair,Furniture,3,120,57.64
38,1039,2024-05-28,Shyam,Lalitpur,Chair,Furniture,4,120,93.87
39,1040,2024-04-26,Nabin,Kathmandu,Notebook,Stationery,4,5,1.68
40,1041,2024-02-21,Ram,Lalitpur,Notebook,Stationery,2,5,1.18
41,1042,2024-05-05,Nabin,Lalitpur,Tablet,Electronics,5,300,128.77
42,1043,2024-05-23,Hari,Bhaktapur,Table,Furniture,1,250,13.14
43,1044,2024-01-07,Hari,Lalitpur,Laptop,Electronics,2,800,245.52
44,1045,2024-06-09,Rita,Lalitpur,Chair,Furniture,5,120,81.18
45,1046,2024-03-10,Nabin,Kathmandu,Notebook,Stationery,5,5,4.04
46,1047,2024-05-20,Asha,Lalitpur,Chair,Furniture,5,120,94.15
47,1048,2024-03-29,Hari,Kathmandu,Phone,Electronics,1,500,85.59
48,1049,2024-01-03,Gita,Lalitpur,Phone,Electronics,5,500,253.59
49,1050,2024-03-13,Sita,Kathmandu,Tablet,Electronics,4,300,290.76

In [13]:
df=pd.read_excel('sales_dataset.xlsx',sheet_name='Sheet2') #printing from the particular sheet

In [18]:
df

   sn    name  salary  city
0   1  rakesh    5000   ktm
1   2    dipi    4000   ltp
2   3     any    8000  krtp
3   4   niman    7000   rjb
4   5    sima    6000   rjb

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sn      5 non-null      int64
 1   name    5 non-null      str
 2   salary  5 non-null      int64
 3   city    5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [21]:
df['salary'].unique()

array([5000, 4000, 8000, 7000, 6000])

In [22]:
df=pd.read_excel('sales_dataset.xlsx',sheet_name='Sales') #printing from the particular sheet

In [23]:
df

,OrderID,Date,Customer,City,Product,Category,Quantity,Price,Profit
0,1001,2024-03-30,Asha,Kathmandu,Phone,Electronics,4,500,284.04
1,1002,2024-03-01,Gita,Bhaktapur,Pen,Stationery,3,2,0.43
2,1003,2024-05-09,Hari,Kathmandu,Table,Furniture,4,250,56.34
3,1004,2024-01-30,Rita,Kathmandu,Notebook,Stationery,4,5,1.41
4,1005,2024-06-19,Hari,Kathmandu,Tablet,Electronics,4,300,145.43
5,1006,2024-05-09,Rita,Bhaktapur,Phone,Electronics,2,500,220.75
6,1007,2024-03-17,Gita,Kathmandu,Pen,Stationery,5,2,2.36
7,1008,2024-06-10,Hari,Lalitpur,Laptop,Electronics,2,800,271.43
8,1009,2024-06-08,Sita,Kathmandu,Pen,Stationery,2,2,0.85
9,1010,2024-02-06,Hari,Kathmandu,Chair,Furniture,5,120,78.66
10,1011,2024-06-13,Shyam,Kathmandu,Table,Furniture,5,250,183.74
11,1012,2024-02-17,Asha,Lalitpur,Pen,Stationery,4,2,1.13
12,1013,2024-03-13,Asha,Lalitpur,Table,Furniture,2,250,101.47
13,1014,2024-02-06,Ram,Bhaktapur,Notebook,Stationery,5,5,4.52
14,1015,2024-03-31,Hari,Kathmandu,Pen,Stationery,1,2,0.15
15,1016,2024-02-25,Nabin,Kathmandu,Chair,Furniture,3,120,60.54
16,1017,2024-01-02,Asha,Kathmandu,Table,Furniture,5,250,195.71
17,1018,2024-04-30,Ram,Kathmandu,Notebook,Stationery,5,5,1.31
18,1019,2024-01-24,Asha,Kathmandu,Table,Furniture,3,250,153.04
19,1020,2024-04-30,Ram,Lalitpur,Pen,Stationery,1,2,0.38
20,1021,2024-03-28,Hari,Kathmandu,Laptop,Electronics,3,800,513.27
21,1022,2024-06-28,Rita,Bhaktapur,Laptop,Electronics,1,800,177.65
22,1023,2024-03-16,Sita,Bhaktapur,Chair,Furniture,2,120,40.30
23,1024,2024-04-06,Gita,Kathmandu,Chair,Furniture,2,120,14.01
24,1025,2024-05-21,Hari,Bhaktapur,Chair,Furniture,4,120,54.19
25,1026,2024-06-27,Gita,Kathmandu,Notebook,Stationery,5,5,4.60
26,1027,2024-03-05,Ram,Kathmandu,Chair,Furniture,3,120,78.27
27,1028,2024-06-09,Shyam,Lalitpur,Table,Furniture,1,250,15.68
28,1029,2024-01-06,Hari,Lalitpur,Laptop,Electronics,3,800,137.76
29,1030,2024-01-02,Rita,Bhaktapur,Tablet,Electronics,3,300,213.99
30,1031,2024-02-20,Nabin,Kathmandu,Notebook,Stationery,5,5,3.64
31,1032,2024-02-11,Sita,Lalitpur,Table,Furniture,3,250,167.86
32,1033,2024-04-09,Asha,Bhaktapur,Phone,Electronics,5,500,511.12
33,1034,2024-02-01,Sita,Lalitpur,Phone,Electronics,3,500,268.76
34,1035,2024-01-31,Gita,Kathmandu,Tablet,Electronics,4,300,90.79
35,1036,2024-01-15,Asha,Bhaktapur,Tablet,Electronics,3,300,68.43
36,1037,2024-03-28,Asha,Lalitpur,Chair,Furniture,4,120,72.44
37,1038,2024-06-15,Sita,Lalitpur,Chair,Furniture,3,120,57.64
38,1039,2024-05-28,Shyam,Lalitpur,Chair,Furniture,4,120,93.87
39,1040,2024-04-26,Nabin,Kathmandu,Notebook,Stationery,4,5,1.68
40,1041,2024-02-21,Ram,Lalitpur,Notebook,Stationery,2,5,1.18
41,1042,2024-05-05,Nabin,Lalitpur,Tablet,Electronics,5,300,128.77
42,1043,2024-05-23,Hari,Bhaktapur,Table,Furniture,1,250,13.14
43,1044,2024-01-07,Hari,Lalitpur,Laptop,Electronics,2,800,245.52
44,1045,2024-06-09,Rita,Lalitpur,Chair,Furniture,5,120,81.18
45,1046,2024-03-10,Nabin,Kathmandu,Notebook,Stationery,5,5,4.04
46,1047,2024-05-20,Asha,Lalitpur,Chair,Furniture,5,120,94.15
47,1048,2024-03-29,Hari,Kathmandu,Phone,Electronics,1,500,85.59
48,1049,2024-01-03,Gita,Lalitpur,Phone,Electronics,5,500,253.59
49,1050,2024-03-13,Sita,Kathmandu,Tablet,Electronics,4,300,290.76

In [31]:
df['TotalSales']=df['Price']*df['Quantity'] #calculating total sales
df

,OrderID,Date,Customer,City,Product,Category,Quantity,Price,Profit,TotalSales
0,1001,2024-03-30,Asha,Kathmandu,Phone,Electronics,4,500,284.04,2000
1,1002,2024-03-01,Gita,Bhaktapur,Pen,Stationery,3,2,0.43,6
2,1003,2024-05-09,Hari,Kathmandu,Table,Furniture,4,250,56.34,1000
3,1004,2024-01-30,Rita,Kathmandu,Notebook,Stationery,4,5,1.41,20
4,1005,2024-06-19,Hari,Kathmandu,Tablet,Electronics,4,300,145.43,1200
5,1006,2024-05-09,Rita,Bhaktapur,Phone,Electronics,2,500,220.75,1000
6,1007,2024-03-17,Gita,Kathmandu,Pen,Stationery,5,2,2.36,10
7,1008,2024-06-10,Hari,Lalitpur,Laptop,Electronics,2,800,271.43,1600
8,1009,2024-06-08,Sita,Kathmandu,Pen,Stationery,2,2,0.85,4
9,1010,2024-02-06,Hari,Kathmandu,Chair,Furniture,5,120,78.66,600
10,1011,2024-06-13,Shyam,Kathmandu,Table,Furniture,5,250,183.74,1250
11,1012,2024-02-17,Asha,Lalitpur,Pen,Stationery,4,2,1.13,8
12,1013,2024-03-13,Asha,Lalitpur,Table,Furniture,2,250,101.47,500
13,1014,2024-02-06,Ram,Bhaktapur,Notebook,Stationery,5,5,4.52,25
14,1015,2024-03-31,Hari,Kathmandu,Pen,Stationery,1,2,0.15,2
15,1016,2024-02-25,Nabin,Kathmandu,Chair,Furniture,3,120,60.54,360
16,1017,2024-01-02,Asha,Kathmandu,Table,Furniture,5,250,195.71,1250
17,1018,2024-04-30,Ram,Kathmandu,Notebook,Stationery,5,5,1.31,25
18,1019,2024-01-24,Asha,Kathmandu,Table,Furniture,3,250,153.04,750
19,1020,2024-04-30,Ram,Lalitpur,Pen,Stationery,1,2,0.38,2
20,1021,2024-03-28,Hari,Kathmandu,Laptop,Electronics,3,800,513.27,2400
21,1022,2024-06-28,Rita,Bhaktapur,Laptop,Electronics,1,800,177.65,800
22,1023,2024-03-16,Sita,Bhaktapur,Chair,Furniture,2,120,40.30,240
23,1024,2024-04-06,Gita,Kathmandu,Chair,Furniture,2,120,14.01,240
24,1025,2024-05-21,Hari,Bhaktapur,Chair,Furniture,4,120,54.19,480
25,1026,2024-06-27,Gita,Kathmandu,Notebook,Stationery,5,5,4.60,25
26,1027,2024-03-05,Ram,Kathmandu,Chair,Furniture,3,120,78.27,360
27,1028,2024-06-09,Shyam,Lalitpur,Table,Furniture,1,250,15.68,250
28,1029,2024-01-06,Hari,Lalitpur,Laptop,Electronics,3,800,137.76,2400
29,1030,2024-01-02,Rita,Bhaktapur,Tablet,Electronics,3,300,213.99,900
30,1031,2024-02-20,Nabin,Kathmandu,Notebook,Stationery,5,5,3.64,25
31,1032,2024-02-11,Sita,Lalitpur,Table,Furniture,3,250,167.86,750
32,1033,2024-04-09,Asha,Bhaktapur,Phone,Electronics,5,500,511.12,2500
33,1034,2024-02-01,Sita,Lalitpur,Phone,Electronics,3,500,268.76,1500
34,1035,2024-01-31,Gita,Kathmandu,Tablet,Electronics,4,300,90.79,1200
35,1036,2024-01-15,Asha,Bhaktapur,Tablet,Electronics,3,300,68.43,900
36,1037,2024-03-28,Asha,Lalitpur,Chair,Furniture,4,120,72.44,480
37,1038,2024-06-15,Sita,Lalitpur,Chair,Furniture,3,120,57.64,360
38,1039,2024-05-28,Shyam,Lalitpur,Chair,Furniture,4,120,93.87,480
39,1040,2024-04-26,Nabin,Kathmandu,Notebook,Stationery,4,5,1.68,20
40,1041,2024-02-21,Ram,Lalitpur,Notebook,Stationery,2,5,1.18,10
41,1042,2024-05-05,Nabin,Lalitpur,Tablet,Electronics,5,300,128.77,1500
42,1043,2024-05-23,Hari,Bhaktapur,Table,Furniture,1,250,13.14,250
43,1044,2024-01-07,Hari,Lalitpur,Laptop,Electronics,2,800,245.52,1600
44,1045,2024-06-09,Rita,Lalitpur,Chair,Furniture,5,120,81.18,600
45,1046,2024-03-10,Nabin,Kathmandu,Notebook,Stationery,5,5,4.04,25
46,1047,2024-05-20,Asha,Lalitpur,Chair,Furniture,5,120,94.15,600
47,1048,2024-03-29,Hari,Kathmandu,Phone,Electronics,1,500,85.59,500
48,1049,2024-01-03,Gita,Lalitpur,Phone,Electronics,5,500,253.59,2500
49,1050,2024-03-13,Sita,Kathmandu,Tablet,Electronics,4,300,290.76,1200

In [35]:
df['TotalSales'].sum() #total sales sum

np.int64(36707)