In [2]:
#feature engineering
#it is the process of using domain knowledge to extract features from raw data
#-creates new features from existing one

In [3]:
# feature selection
# process of selecting the useful features from the group of features
# -reduce unnecessary features
# -reduce dimension

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.DataFrame({
    "Age":[25,np.nan,30],
    "Salary":[50000,60000,70000]
})
df

    Age  Salary
0  25.0   50000
1   NaN   60000
2  30.0   70000

In [32]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df

    Age  Salary
0  25.0   50000
1  27.5   60000
2  30.0   70000

In [33]:
df=pd.DataFrame({
    "Age":[20,np.nan,30,28,35,np.nan],
    "Salary":[50000,60000,70000,55000,900000,65000000],
    "Gender":['male','female','male','female','female','male'],
    "Department":['HR','IT','Finance','IT','HR','Marketing'],
    "City": ['kathmandu','pokhara','kathmandu','pokhara','lalitpur','birgunj']
})
df

    Age    Salary  Gender Department       City
0  20.0     50000    male         HR  kathmandu
1   NaN     60000  female         IT    pokhara
2  30.0     70000    male    Finance  kathmandu
3  28.0     55000  female         IT    pokhara
4  35.0    900000  female         HR   lalitpur
5   NaN  65000000    male  Marketing    birgunj

In [34]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df

     Age    Salary  Gender Department       City
0  20.00     50000    male         HR  kathmandu
1  28.25     60000  female         IT    pokhara
2  30.00     70000    male    Finance  kathmandu
3  28.00     55000  female         IT    pokhara
4  35.00    900000  female         HR   lalitpur
5  28.25  65000000    male  Marketing    birgunj

In [35]:
#create new feature
df['Age_Group']=pd.cut(
    df['Age'],
    bins=[0,18,30,50,100],
    labels=['young','adult','middle_age','senior']
)
df[['Age','Age_Group']]

     Age   Age_Group
0  20.00       adult
1  28.25       adult
2  30.00       adult
3  28.00       adult
4  35.00  middle_age
5  28.25       adult

In [36]:
df['Salary_Level']=pd.cut(
    df['Salary'],
    bins=[0,60000,1000000,float('inf')],
    labels=['low','medium','high']
)
df[['Salary','Salary_Level']]

     Salary Salary_Level
0     50000          low
1     60000          low
2     70000       medium
3     55000          low
4    900000       medium
5  65000000         high

In [37]:
df

     Age    Salary  Gender Department       City   Age_Group Salary_Level
0  20.00     50000    male         HR  kathmandu       adult          low
1  28.25     60000  female         IT    pokhara       adult          low
2  30.00     70000    male    Finance  kathmandu       adult       medium
3  28.00     55000  female         IT    pokhara       adult          low
4  35.00    900000  female         HR   lalitpur  middle_age       medium
5  28.25  65000000    male  Marketing    birgunj       adult         high

In [38]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(drop='first',sparse_output=False)
encoded=encoder.fit_transform(df[['Gender','Department','City']])
encoded

array([[1., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 0.]])

In [39]:
df_encoded=pd.get_dummies(
    df,
    columns=['Gender','Department','City','Age_Group','Salary_Level'],
    dtype=int
)
df_encoded

,Age,Salary,Gender_female,Gender_male,Department_Finance,Department_HR,Department_IT,Department_Marketing,City_birgunj,City_kathmandu,City_lalitpur,City_pokhara,Age_Group_young,Age_Group_adult,Age_Group_middle_age,Age_Group_senior,Salary_Level_low,Salary_Level_medium,Salary_Level_high
0,20.00,50000,0,1,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0
1,28.25,60000,1,0,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0
2,30.00,70000,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0
3,28.00,55000,1,0,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0
4,35.00,900000,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0
5,28.25,65000000,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1

In [40]:
encoded_df=pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['Gender','Department','City']))
encoded_df

,Gender_male,Department_HR,Department_IT,Department_Marketing,City_kathmandu,City_lalitpur,City_pokhara
0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.0,1.0,0.0,0.0,0.0,1.0,0.0
5,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [41]:
df

     Age    Salary  Gender Department       City   Age_Group Salary_Level
0  20.00     50000    male         HR  kathmandu       adult          low
1  28.25     60000  female         IT    pokhara       adult          low
2  30.00     70000    male    Finance  kathmandu       adult       medium
3  28.00     55000  female         IT    pokhara       adult          low
4  35.00    900000  female         HR   lalitpur  middle_age       medium
5  28.25  65000000    male  Marketing    birgunj       adult         high

In [42]:
X=df.drop(columns=['Salary'])
X

     Age  Gender Department       City   Age_Group Salary_Level
0  20.00    male         HR  kathmandu       adult          low
1  28.25  female         IT    pokhara       adult          low
2  30.00    male    Finance  kathmandu       adult       medium
3  28.00  female         IT    pokhara       adult          low
4  35.00  female         HR   lalitpur  middle_age       medium
5  28.25    male  Marketing    birgunj       adult         high

In [48]:
y=df['Salary']
y

0       50000
1       60000
2       70000
3       55000
4      900000
5    65000000
Name: Salary, dtype: int64