In [1]:
#grouping and aggragation
import pandas as pd

In [31]:
df=pd.DataFrame({
    "Department":['IT','HR','IT','Finance','HR','Finance'],
    "Employee":['Rakhi','Sikha','Anisha','Priya','Jhyoti','Ramila'],
    "Salary":[5000,6000,7000,8000,5500,9000],
    "Age":[25,30,28,35,32,40]
})

In [32]:
sal_sum=df.groupby("Department")["Salary"].sum()

In [33]:
sal_sum

Department
Finance    17000
HR         11500
IT         12000
Name: Salary, dtype: int64

In [34]:
print(type(sal_sum))

<class 'pandas.Series'>

In [35]:
dept_count=sal_sum=df.groupby("Department")["Salary"].count()

In [36]:
dept_count

Department
Finance    2
HR         2
IT         2
Name: Salary, dtype: int64

In [37]:
sal_mean=df.groupby("Department")["Salary"].mean()

In [38]:
sal_mean

Department
Finance    8500.0
HR         5750.0
IT         6000.0
Name: Salary, dtype: float64

In [39]:
sal_min=df.groupby("Department")["Salary"].min()

In [40]:
sal_min

Department
Finance    8000
HR         5500
IT         5000
Name: Salary, dtype: int64

In [41]:
sal_max=df.groupby("Department")["Salary"].max()

In [42]:
sal_max

Department
Finance    9000
HR         6000
IT         7000
Name: Salary, dtype: int64

In [43]:
result=df.groupby("Department").agg({
    "Salary":['sum','mean','max'],
    "Age":['min','max']
})
result

           Salary               Age
              sum    mean   max min max
Department
Finance     17000  8500.0  9000  35  40
HR          11500  5750.0  6000  30  32
IT          12000  6000.0  7000  25  28

In [44]:
#total sal of IT dept
total_IT_dept_sal=df[df['Department']=='IT']['Salary'].sum()
total_IT_dept_sal

np.int64(12000)

In [45]:
avg_IT_dept_sal = df[df['Department'] == 'IT']['Salary'].mean()
avg_IT_dept_sal

np.float64(6000.0)

In [46]:
#calculate the difference of salary between IT dept and finance dept
it=df[df['Department']=='IT']['Salary'].sum()
fin=df[df['Department']=='Finance']['Salary'].sum()
diff=it-fin
diff

np.int64(-5000)

In [52]:

Gender={
    "Rakhi":"Female",
    "Sikha":"Female",
    "Anisha":"Female",
    "Priya":"Female",
    "Jhyoti":"Female",
    "Ramila":"Female"
}

In [54]:
df['Gender']=df['Employee'].map(Gender)

In [55]:
df

  Department Employee  Salary  Age  Gender
0         IT    Rakhi    5000   25  Female
1         HR    Sikha    6000   30  Female
2         IT   Anisha    7000   28  Female
3    Finance    Priya    8000   35  Female
4         HR   Jhyoti    5500   32  Female
5    Finance   Ramila    9000   40  Female

In [56]:
#sum on basis of dept and gender
res=df.groupby(["Department","Gender"])["Salary"].sum()
res

Department  Gender
Finance     Female    17000
HR          Female    11500
IT          Female    12000
Name: Salary, dtype: int64

In [57]:
result=(
    df.groupby("Department").agg(
        avg_sal=("Salary","mean"),
        emp_count=("Employee","count")
    )
    .reset_index()
)
result

  Department  avg_sal  emp_count
0    Finance   8500.0          2
1         HR   5750.0          2
2         IT   6000.0          2

In [58]:
print(result['Department'])

0    Finance
1         HR
2         IT
Name: Department, dtype: str

In [59]:
print(result['avg_sal'])

0    8500.0
1    5750.0
2    6000.0
Name: avg_sal, dtype: float64

In [61]:
print(result["emp_count"])

0    2
1    2
2    2
Name: emp_count, dtype: int64

In [62]:
print(result['avg_sal'][0])

8500.0