In [28]:
#merging
import pandas as pd
employees=pd.DataFrame({
    "EmpID":[1,2,3],
    "Name":["Rakesh","Sikha","Anil"]
})
salaries=pd.DataFrame({
    "EmpID":[1,2,4],
    "Salary":[5000,7000,6000]
})

In [29]:
mdf=pd.merge(employees,salaries,on="EmpID")
mdf

   EmpID    Name  Salary
0      1  Rakesh    5000
1      2   Sikha    7000

In [30]:
ldf=pd.merge(employees,salaries,on="EmpID",how="left")
ldf

   EmpID    Name  Salary
0      1  Rakesh  5000.0
1      2   Sikha  7000.0
2      3    Anil     NaN

In [31]:
rdf=pd.merge(employees,salaries,on="EmpID",how="right")
rdf

   EmpID    Name  Salary
0      1  Rakesh    5000
1      2   Sikha    7000
2      4     NaN    6000

In [32]:
df1=pd.DataFrame({
    "Name":["Rakesh","Sikha"],
    "Age":[25,30]
})
df2=pd.DataFrame({
    "Name":["Anil","Priya"],
    "Age":[22,28]
})

In [33]:
cdf=pd.concat([df1,df2],ignore_index=True)
cdf

     Name  Age
0  Rakesh   25
1   Sikha   30
2    Anil   22
3   Priya   28

In [34]:
employees=pd.DataFrame({
    "EmpID":[1,2,3],
    "Name":["Rakesh","Sikha","Anil"]
})
salaries=pd.DataFrame({
    "EmpID":[1,2,4],
    "Salary":[5000,7000,6000]
})

In [35]:
outer_merge=pd.merge(employees,salaries,on="EmpID",how="outer")
outer_merge

   EmpID    Name  Salary
0      1  Rakesh  5000.0
1      2   Sikha  7000.0
2      3    Anil     NaN
3      4     NaN  6000.0

In [36]:
left=pd.DataFrame({
    "Name":["Rakesh","Sikha","Anil"]
},index=[1,2,3])
right=pd.DataFrame({
    "Salary":[5000,7000,6000]
},index=[1,2,4])

In [37]:
df=left.join(right)
df

     Name  Salary
1  Rakesh  5000.0
2   Sikha  7000.0
3    Anil     NaN

In [38]:
inner=left.join(right,how="inner") #only common
inner

     Name  Salary
1  Rakesh    5000
2   Sikha    7000

In [39]:
left.join(right,how="right")

     Name  Salary
1  Rakesh    5000
2   Sikha    7000
4     NaN    6000

In [40]:
left.join(right,how="outer") #all

     Name  Salary
1  Rakesh  5000.0
2   Sikha  7000.0
3    Anil     NaN
4     NaN  6000.0

In [41]:
order=pd.DataFrame({
    "order_id":[1,2,3,4],
    "customer_id":[101,102,103,104],
    "amount":[250,150,300,200]
})
customers=pd.DataFrame({
    "customer_id":[101,102,105],
    "name":["Alice","Bob","Eve"]
})

In [43]:
cdf=pd.concat([order,customers],ignore_index=True)
cdf

   order_id  customer_id  amount   name
0       1.0          101   250.0    NaN
1       2.0          102   150.0    NaN
2       3.0          103   300.0    NaN
3       4.0          104   200.0    NaN
4       NaN          101     NaN  Alice
5       NaN          102     NaN    Bob
6       NaN          105     NaN    Eve

In [48]:
mdf=pd.merge(order,customers,on="customer_id")
mdf

   order_id  customer_id  amount   name
0         1          101     250  Alice
1         2          102     150    Bob