In [1]:
# Project: We will web scrap the data and same in dataframe

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url="https://books.toscrape.com/"

In [5]:
response=requests.get(url)
response

In [17]:
soup=BeautifulSoup(response.text,"html.parser")
# soup

In [31]:
books=[]

In [32]:
for book in soup.find_all("article",class_="product_pod"):
    title=book.h3.a['title']
    price=book.find("p",class_="price_color").text
    rating=book.find('p')['class'][1]
    books.append({
        'Title':title,
        'Price':price,
        'Rating':rating
    })

In [33]:
df=pd.DataFrame(books)
df

                                                Title    Price Rating
0                                A Light in the Attic  Â£51.77  Three
1                                  Tipping the Velvet  Â£53.74    One
2                                          Soumission  Â£50.10    One
3                                       Sharp Objects  Â£47.82   Four
4               Sapiens: A Brief History of Humankind  Â£54.23   Five
5                                     The Requiem Red  Â£22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60   Four
9                                     The Black Maria  Â£52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99    Two
11                              Shakespeare's Sonnets  Â£20.66   Four
12                                        Set Me Free  Â£17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29   Five
14                          Rip it Up and Start Again  Â£35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25  Three
16                                               Olio  Â£23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59    One
18                       Libertarianism for Beginners  Â£51.33    Two
19                            It's Only the Himalayas  Â£45.17    Two

In [34]:
df['Price']=df['Price'].replace(r'[^0-9.]','',regex=True)
df['Price']=df['Price'].astype(float)

In [35]:
df['Price']

0     51.77
1     53.74
2     50.10
3     47.82
4     54.23
5     22.65
6     33.34
7     17.93
8     22.60
9     52.15
10    13.99
11    20.66
12    17.46
13    52.29
14    35.02
15    57.25
16    23.88
17    37.59
18    51.33
19    45.17
Name: Price, dtype: float64

In [36]:
df

                                                Title  Price Rating
0                                A Light in the Attic  51.77  Three
1                                  Tipping the Velvet  53.74    One
2                                          Soumission  50.10    One
3                                       Sharp Objects  47.82   Four
4               Sapiens: A Brief History of Humankind  54.23   Five
5                                     The Requiem Red  22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  22.60   Four
9                                     The Black Maria  52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99    Two
11                              Shakespeare's Sonnets  20.66   Four
12                                        Set Me Free  17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29   Five
14                          Rip it Up and Start Again  35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  57.25  Three
16                                               Olio  23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  37.59    One
18                       Libertarianism for Beginners  51.33    Two
19                            It's Only the Himalayas  45.17    Two

In [37]:
df.to_csv('book_detail.csv')

In [38]:
d=pd.read_csv('book_detail.csv')
d

,Unnamed: 0,Title,Price,Rating
0,0,A Light in the Attic,51.77,Three
1,1,Tipping the Velvet,53.74,One
2,2,Soumission,50.10,One
3,3,Sharp Objects,47.82,Four
4,4,Sapiens: A Brief History of Humankind,54.23,Five
5,5,The Requiem Red,22.65,One
6,6,The Dirty Little Secrets of Getting Your Dream...,33.34,Four
7,7,The Coming Woman: A Novel Based on the Life of...,17.93,Three
8,8,The Boys in the Boat: Nine Americans and Their...,22.60,Four
9,9,The Black Maria,52.15,One
10,10,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99,Two
11,11,Shakespeare's Sonnets,20.66,Four
12,12,Set Me Free,17.46,Five
13,13,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,Five
14,14,Rip it Up and Start Again,35.02,Five
15,15,Our Band Could Be Your Life: Scenes from the A...,57.25,Three
16,16,Olio,23.88,One
17,17,Mesaerion: The Best Science Fiction Stories 18...,37.59,One
18,18,Libertarianism for Beginners,51.33,Two
19,19,It's Only the Himalayas,45.17,Two